export const clues = {
    noun: [
        'man',
        'woman',
        'child',
        'technology',
        'vehicle',
        'structure',
        'film',
        'container',
        'opposite',
        'material',
        'name',
        'medicine',
        'mouth',
        'head',
        'event',
        'love',
        'music',
        'object',
        'process',
        'place',
        'day',
        'night',
        'feeling',
        'illness',
        'north',
        'south',
        'west',
        'east',
        'animal',
        'plant',
        'science',
        'religion',
        'earth',
        'air',
        'website',
        'social media',
        'body',
        'economy',
        'picture',
        'conflict',
        'sight',
        'journey',
        'city',
        'country',
        'politics',
        'metal',
        'wood',
        'sky',
        'job',
        'sport',
        'time',
        'circle',
        'literature',
        'weather',
    ],
    verb: [
        'eat',
        'drink',
        'give',
        'take',
        'turn',
        'fly',
        'run',
        'sit',
        'play',
        'make',
        'make',
        'read',
        'write',
        'jump',
        'smell',
        'see',
        'speak',
        'hear',
        'shoot',
    ],
    preposition: [
        'many',
        'for',
        'under',
        'over',
        'out',
        'on',
        'by',
        'in',
        'not',
        'above',
        'below',
        'left',
        'right',
        'zero',
        'one',
        'two',
        'times',
        'with',
    ],
    adjective: [
        'white',
        'black',
        'green',
        'red',
        'blue',
        'orange',
        'yellow',
        'brown',
        'grey',
        'transparent',
        'long',
        'thin',
        'loud',
        'funny',
        'fictitious',
        'sweet',
        'divided',
        'historical',
        'dead',
        'hot',
        'cold',
        'bad',
        'good',
        'big',
        'small',
        'old',
        'new',
        'strong',
        'weak',
        'beautiful',
        'bright',
        'soft',
        'heavy',
        'fast',
    ],
};

export const stories = {
    'Animals, Plants, Creatures': ['Mammoth', 'Wolf', 'Tick', 'Bear', 'Goblin', 'Fairy'],
    'Travel, Outdoors, History': [
        'Tour de France',
        'Amsterdam',
        'Buckingham Palace',
        'Barcelona',
        'Oasis',
        'Washington',
    ],
    'Food & Drink': ['Wasabi', 'Caviar', 'Energy drink', 'Pancake', 'Dessert', 'Radish'],
    'Web & Social Media': [
        'Playstation',
        'E-commerce',
        'Post',
        'ROFL',
        'Password',
        'Snapchat',
        'Pepe',
    ],
    'Emotions & Miscellaneous': [
        'Paw',
        'Rumor',
        'Driving instructor',
        'Feather',
        'Hot-water bottle',
        'Compass',
    ],
    'Science, Technology, Religion': [
        'Black hole',
        'Brain',
        'Devil',
        'Rust',
        'Logbook',
        'Communion',
    ],
    'Movies, Music, Literature': [
        'Photograph',
        'Karl Lagerfeld',
        'The Hobbit',
        'LeBron James',
        'Mark Twain',
        'Step Up',
    ],
};
