export const clues = {
    noun: [
        'man',
        'woman',
        'child',
        'technology',
        'vehicle',
        'structure',
        'film',
        'container',
        'opposite',
        'material',
        'name',
        'medicine',
        'mouth',
        'head',
        'event',
        'love',
        'music',
        'object',
        'process',
        'place',
        'day',
        'night',
        'feeling',
        'illness',
        'north',
        'south',
        'west',
        'east',
        'animal',
        'plant',
        'science',
        'religion',
        'earth',
        'air',
        'website',
        'social media',
        'body',
        'economy',
        'picture',
        'conflict',
        'sight',
        'journey',
        'city',
        'country',
        'politics',
        'metal',
        'wood',
        'sky',
        'job',
        'sport',
        'time',
        'circle',
        'literature',
        'weather',
    ],
    verb: [
        'eat',
        'drink',
        'give',
        'take',
        'turn',
        'fly',
        'run',
        'sit',
        'play',
        'make',
        'make',
        'read',
        'write',
        'jump',
        'smell',
        'see',
        'speak',
        'hear',
        'shoot',
    ],
    preposition: [
        'many',
        'for',
        'under',
        'over',
        'out',
        'on',
        'by',
        'in',
        'not',
        'above',
        'below',
        'left',
        'right',
        'zero',
        'one',
        'two',
        'times',
        'with',
    ],
    adjective: [
        'white',
        'black',
        'green',
        'red',
        'blue',
        'orange',
        'yellow',
        'brown',
        'grey',
        'transparent',
        'long',
        'thin',
        'loud',
        'funny',
        'fictitious',
        'sweet',
        'divided',
        'historical',
        'dead',
        'hot',
        'cold',
        'bad',
        'good',
        'big',
        'small',
        'old',
        'new',
        'strong',
        'weak',
        'beautiful',
        'bright',
        'soft',
        'heavy',
        'fast',
    ],
};

const stories = [
    {
        category: 'Animals, Plants, Creatures',
        words: ['Mammoth', 'Wolf', 'Tick', 'Bear', 'Goblin', 'Fairy'],
    },
    {
        category: 'Travel, Outdoors, History',
        words: [
            'Tour de France',
            'Amsterdam',
            'Buckingham Palace',
            'Barcelona',
            'Oasis',
            'Washington',
        ],
    },
    {
        category: 'Food & Drink',
        words: ['Wasabi', 'Caviar', 'Energy drink', 'Pancake', 'Dessert', 'Radish'],
    },
    {
        category: 'Web & Social Media',
        words: ['Playstation', 'E-commerce', 'Post', 'ROFL', 'Password', 'Snapchat', 'Pepe'],
    },
    {
        category: 'Emotions & Miscellaneous',
        words: ['Paw', 'Rumor', 'Driving instructor', 'Feather', 'Hot-water bottle', 'Compass'],
    },
    {
        category: 'Science, Technology, Religion',
        words: ['Black hole', 'Brain', 'Devil', 'Rust', 'Logbook', 'Communion'],
    },
    {
        category: 'Movies, Music, Literature',
        words: [
            'Photograph',
            'Karl Lagerfeld',
            'The Hobbit',
            'LeBron James',
            'Mark Twain',
            'Step Up',
        ],
    },
];
